/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.customJFrame;

import Dao.CustomerDao;
import Dao.VehicleDao;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 健鑫
 */
public class FindCustomerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FindCustomerJFrame
     */
    public FindCustomerJFrame() {
        initComponents();
    }
    private JTable jTable;
    private JLabel jLabel;
    public FindCustomerJFrame(JTable jt,JLabel jl) {
        jTable=jt;
        jLabel=jl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CustomerFind_Name_TextField = new javax.swing.JTextField();
        CustomerFind_TELL_TextField = new javax.swing.JTextField();
        CustomerFind_Address_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CustomerFind_CardNumber_TextField = new javax.swing.JTextField();
        CustomerFind_OK_Button = new javax.swing.JButton();
        CustomerFind_Cancel_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("姓名：");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("手机号：");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("地址：");

        CustomerFind_Name_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        CustomerFind_TELL_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        CustomerFind_Address_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("身份证号：");

        CustomerFind_CardNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        CustomerFind_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        CustomerFind_OK_Button.setText("查找");
        CustomerFind_OK_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustomerFind_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerFind_OK_ButtonActionPerformed(evt);
            }
        });

        CustomerFind_Cancel_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        CustomerFind_Cancel_Button.setText("取消");
        CustomerFind_Cancel_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustomerFind_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerFind_Cancel_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CustomerFind_OK_Button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustomerFind_Cancel_Button)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addComponent(CustomerFind_Address_TextField)
                    .addComponent(CustomerFind_CardNumber_TextField)
                    .addComponent(CustomerFind_TELL_TextField)
                    .addComponent(CustomerFind_Name_TextField))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(CustomerFind_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CustomerFind_TELL_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CustomerFind_Address_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CustomerFind_CardNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerFind_OK_Button)
                    .addComponent(CustomerFind_Cancel_Button))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerFind_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerFind_OK_ButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel)jTable.getModel();
        //声明list
        ArrayList list=new ArrayList();
        //声明map
        Map rowDataMap=new HashMap();
        //获取数值
        String nameString=CustomerFind_Name_TextField.getText();
        String tellString=CustomerFind_TELL_TextField.getText();
        String addressString=CustomerFind_Address_TextField.getText();
        String cardnomberString=CustomerFind_CardNumber_TextField.getText();
        //查询
        list=new CustomerDao().list(nameString, tellString, addressString, cardnomberString);
        //没有查到结果时报错
        if(list==null){
             JOptionPane.showMessageDialog(null, "没有找到查询结果", "查询失败", JOptionPane.ERROR_MESSAGE); 
        }else{
            //计数器，记录第几行
            int i=0;
            //迭代器
            Iterator it1 = list.iterator();
            //重置table内容，避免第二次查询结果少于第一次时，第一次的内容依然存在
            tableModel.setRowCount(list.size());
            //遍历
            while(it1.hasNext()){
                rowDataMap=(Map) it1.next();
                //显示
//`c_name`, `c_card_number`, `c_integration`, `c_tell`, `c_sex`, `c_address`, `c_cash`, `c_remark`
                tableModel.setValueAt(rowDataMap.get("c_id"), i,0);
                tableModel.setValueAt(rowDataMap.get("c_name"), i, 1);
                tableModel.setValueAt(rowDataMap.get("c_card_number"), i, 2);
                tableModel.setValueAt(rowDataMap.get("c_tell"), i, 3);
                tableModel.setValueAt(rowDataMap.get("c_sex"), i, 4);
                tableModel.setValueAt(rowDataMap.get("c_integration"), i, 5);
                tableModel.setValueAt(rowDataMap.get("c_cash"), i, 6);
                tableModel.setValueAt(rowDataMap.get("c_address"), i, 7);
                tableModel.setValueAt(rowDataMap.get("c_remark"), i, 8);
                
                i++;
            } 
            //显示条目数量
            jLabel.setText(String.valueOf(i));
        }
        
     //关闭
     dispose();
    }//GEN-LAST:event_CustomerFind_OK_ButtonActionPerformed

    private void CustomerFind_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerFind_Cancel_ButtonActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CustomerFind_Cancel_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindCustomerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerFind_Address_TextField;
    private javax.swing.JButton CustomerFind_Cancel_Button;
    private javax.swing.JTextField CustomerFind_CardNumber_TextField;
    private javax.swing.JTextField CustomerFind_Name_TextField;
    private javax.swing.JButton CustomerFind_OK_Button;
    private javax.swing.JTextField CustomerFind_TELL_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
