/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.customJFrame;

import Dao.CustomerDao;
import Po.Customer;

/**
 *
 * @author 健鑫
 */
public class UpdateCustomerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCustomerJFrame
     */
    private Customer customer;
    public UpdateCustomerJFrame(Customer c) {
        customer=c;
        initComponents();
    }
    public UpdateCustomerJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateCustomer_Name_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        updateCustomer_CardNumber_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        updateCustomer_Sex_ComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        updateCustomer_TELL_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        updateCustomer_integration_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        updateCustomer_Cash_TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        updateCustomer_Address_TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateCustomer_Remark_TextArea = new javax.swing.JTextArea();
        updateCustomer_Cancel_Button = new javax.swing.JButton();
        updateCustomer_OK_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("客户姓名：");

        updateCustomer_Name_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_Name_TextField.setText(customer.getC_Name());

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("身份证号：");

        updateCustomer_CardNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_CardNumber_TextField.setText(customer.getC_Card_Number());

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("客户性别：");

        updateCustomer_Sex_ComboBox.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_Sex_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "男", "女" }));
        updateCustomer_Sex_ComboBox.setSelectedItem(customer.getC_Sex());

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("手机号：");

        updateCustomer_TELL_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_TELL_TextField.setText(customer.getC_Tell());

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("积分:");

        updateCustomer_integration_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_integration_TextField.setText(String.valueOf(customer.getC_Integration())
        );

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("现金：");

        updateCustomer_Cash_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_Cash_TextField.setText(String.valueOf(customer.getC_Cash())
        );

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("地址：");

        updateCustomer_Address_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_Address_TextField.setText(customer.getC_Address());

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel8.setText("备注:");

        updateCustomer_Remark_TextArea.setColumns(20);
        updateCustomer_Remark_TextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        updateCustomer_Remark_TextArea.setRows(5);
        updateCustomer_Remark_TextArea.setText(customer.getC_Remark());
        jScrollPane1.setViewportView(updateCustomer_Remark_TextArea);

        updateCustomer_Cancel_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_Cancel_Button.setText("取消");
        updateCustomer_Cancel_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCustomer_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomer_Cancel_ButtonActionPerformed(evt);
            }
        });

        updateCustomer_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCustomer_OK_Button.setText("确定");
        updateCustomer_OK_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCustomer_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomer_OK_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(updateCustomer_OK_Button)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateCustomer_CardNumber_TextField)
                            .addComponent(updateCustomer_Name_TextField)
                            .addComponent(updateCustomer_TELL_TextField)
                            .addComponent(updateCustomer_integration_TextField)
                            .addComponent(updateCustomer_Address_TextField)
                            .addComponent(updateCustomer_Cash_TextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateCustomer_Sex_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 230, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(updateCustomer_Cancel_Button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(updateCustomer_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(updateCustomer_CardNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(updateCustomer_Sex_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(updateCustomer_TELL_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(updateCustomer_integration_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(updateCustomer_Cash_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(updateCustomer_Address_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCustomer_Cancel_Button)
                    .addComponent(updateCustomer_OK_Button))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateCustomer_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomer_Cancel_ButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_updateCustomer_Cancel_ButtonActionPerformed

    private void updateCustomer_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomer_OK_ButtonActionPerformed
        // TODO add your handling code here:
        customer.setC_Address(updateCustomer_Address_TextField.getText());
        customer.setC_Card_Number(updateCustomer_CardNumber_TextField.getText());
        customer.setC_Cash(Float.valueOf(updateCustomer_Cash_TextField.getText()));
        customer.setC_Integration(Float.valueOf(updateCustomer_integration_TextField.getText()));
        customer.setC_Name(updateCustomer_Name_TextField.getText());
        customer.setC_Remark(updateCustomer_Remark_TextArea.getText());
        customer.setC_Sex(String.valueOf(updateCustomer_Sex_ComboBox.getSelectedItem()));
        customer.setC_Tell(updateCustomer_TELL_TextField.getText());
        new CustomerDao().update(customer);
        dispose();
    }//GEN-LAST:event_updateCustomer_OK_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField updateCustomer_Address_TextField;
    private javax.swing.JButton updateCustomer_Cancel_Button;
    private javax.swing.JTextField updateCustomer_CardNumber_TextField;
    private javax.swing.JTextField updateCustomer_Cash_TextField;
    private javax.swing.JTextField updateCustomer_Name_TextField;
    private javax.swing.JButton updateCustomer_OK_Button;
    private javax.swing.JTextArea updateCustomer_Remark_TextArea;
    private javax.swing.JComboBox<String> updateCustomer_Sex_ComboBox;
    private javax.swing.JTextField updateCustomer_TELL_TextField;
    private javax.swing.JTextField updateCustomer_integration_TextField;
    // End of variables declaration//GEN-END:variables
}
