/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.insuranceJFrame;

import Dao.CustomerDao;
import Dao.InsuranceDao;
import JFrame.customJFrame.CustomerChooseJFrame;
import Po.Insurance;
import Po.Vehicle;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 健鑫
 */
public class AddInsuranceJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddInsuranceJFrame
     */
    private Vehicle vehicle;
    public AddInsuranceJFrame() {
        initComponents();
    }
    public AddInsuranceJFrame(Vehicle v) {
        vehicle=v;
        jLabel=new javax.swing.JLabel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addInsurance_Number_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addInsurance_PlantNumber_TextField = new javax.swing.JTextField();
        addInsurance_ChooseCustomer_Button = new javax.swing.JButton();
        addInsurance_CustomerName_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addInsurance_Brand_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addInsurance_Type_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addInsurance_Money_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addInsurance_Tax_TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addInsurance_Sum_TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addInsurance_StartDate_TextField = new javax.swing.JTextField();
        addInsurance_OK_Button = new javax.swing.JButton();
        addInsurance_Cancel_Button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addInsurance_Remark_TextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        addInsurance_Date_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("添加保单");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("保单号：");

        addInsurance_Number_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("车牌号：");

        addInsurance_PlantNumber_TextField.setEditable(false);
        addInsurance_PlantNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addInsurance_PlantNumber_TextField.setText(vehicle.getV_Plante_Nomber());

        addInsurance_ChooseCustomer_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addInsurance_ChooseCustomer_Button.setText("选择被保险人");
        addInsurance_ChooseCustomer_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addInsurance_ChooseCustomer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInsurance_ChooseCustomer_ButtonActionPerformed(evt);
            }
        });

        addInsurance_CustomerName_TextField.setEditable(false);
        addInsurance_CustomerName_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("保险公司：");

        addInsurance_Brand_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("保险类型：");

        addInsurance_Type_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("保费：");

        addInsurance_Money_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addInsurance_Money_TextField.setText("0");
        addInsurance_Money_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addInsurance_Money_TextFieldFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("税：");

        addInsurance_Tax_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addInsurance_Tax_TextField.setText("0");
        addInsurance_Tax_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addInsurance_Tax_TextFieldFocusLost(evt);
            }
        });
        addInsurance_Tax_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInsurance_Tax_TextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("总价：");

        addInsurance_Sum_TextField.setEditable(false);
        addInsurance_Sum_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel8.setText("保单生效时间：");

        addInsurance_StartDate_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addInsurance_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addInsurance_OK_Button.setText("确定");
        addInsurance_OK_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addInsurance_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInsurance_OK_ButtonActionPerformed(evt);
            }
        });

        addInsurance_Cancel_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addInsurance_Cancel_Button.setText("取消");
        addInsurance_Cancel_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addInsurance_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInsurance_Cancel_ButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel9.setText("备注");

        addInsurance_Remark_TextArea.setColumns(20);
        addInsurance_Remark_TextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        addInsurance_Remark_TextArea.setRows(5);
        jScrollPane1.setViewportView(addInsurance_Remark_TextArea);

        jLabel10.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel10.setText("投保时间：");

        addInsurance_Date_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(addInsurance_ChooseCustomer_Button)
                        .addGap(26, 26, 26)
                        .addComponent(addInsurance_CustomerName_TextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addInsurance_Number_TextField)
                                    .addComponent(addInsurance_PlantNumber_TextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(addInsurance_OK_Button))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addInsurance_StartDate_TextField)
                                    .addComponent(addInsurance_Brand_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addInsurance_Type_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addInsurance_Sum_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addInsurance_Tax_TextField)
                                    .addComponent(addInsurance_Money_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addInsurance_Cancel_Button)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(addInsurance_Date_TextField))))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInsurance_ChooseCustomer_Button)
                    .addComponent(addInsurance_CustomerName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addInsurance_PlantNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addInsurance_Number_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addInsurance_Brand_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addInsurance_Type_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addInsurance_Money_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addInsurance_Tax_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addInsurance_Sum_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addInsurance_StartDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addInsurance_Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInsurance_OK_Button)
                    .addComponent(addInsurance_Cancel_Button))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addInsurance_ChooseCustomer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInsurance_ChooseCustomer_ButtonActionPerformed
        // TODO add your handling code here:
        new CustomerChooseJFrame(jLabel, addInsurance_CustomerName_TextField).setVisible(true);
        
    }//GEN-LAST:event_addInsurance_ChooseCustomer_ButtonActionPerformed

    private void addInsurance_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInsurance_OK_ButtonActionPerformed
        // TODO add your handling code here:
        Insurance insurance=new Insurance();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");  
        java.util.Date date=null;
        insurance.setI_Custmoer_ID(Integer.valueOf(jLabel.getText()));
        insurance.setI_Brand(addInsurance_Brand_TextField.getText());
        insurance.setI_Customer_Name(addInsurance_CustomerName_TextField.getText());
        String dstr=addInsurance_Date_TextField.getText();  
        try { 
            date=sdf.parse(dstr);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateInsuranceJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        insurance.setI_Date(date);
        insurance.setI_Money(Float.valueOf(addInsurance_Money_TextField.getText()));
        insurance.setI_Paper_ID(addInsurance_Number_TextField.getText());
        insurance.setI_Remark(addInsurance_Remark_TextArea.getText());
        dstr=addInsurance_StartDate_TextField.getText();  
        try { 
            date=sdf.parse(dstr);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateInsuranceJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        insurance.setI_Start_Date(date);
        insurance.setI_Sum(Float.valueOf(addInsurance_Sum_TextField.getText()));
        insurance.setI_Tax(Float.valueOf(addInsurance_Tax_TextField.getText()));
        insurance.setI_Type(addInsurance_Type_TextField.getText());
        new InsuranceDao().add(insurance, new CustomerDao().find(Integer.valueOf(jLabel.getText())), vehicle);
        dispose();
    }//GEN-LAST:event_addInsurance_OK_ButtonActionPerformed

    private void addInsurance_Tax_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInsurance_Tax_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addInsurance_Tax_TextFieldActionPerformed

    private void addInsurance_Money_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addInsurance_Money_TextFieldFocusLost
        // TODO add your handling code here:
        addInsurance_Sum_TextField.setText(String.valueOf(Float.valueOf(addInsurance_Money_TextField.getText())+Float.valueOf(addInsurance_Tax_TextField.getText())));
    }//GEN-LAST:event_addInsurance_Money_TextFieldFocusLost

    private void addInsurance_Tax_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addInsurance_Tax_TextFieldFocusLost
        // TODO add your handling code here:
        addInsurance_Sum_TextField.setText(String.valueOf(Float.valueOf(addInsurance_Money_TextField.getText())+Float.valueOf(addInsurance_Tax_TextField.getText())));

    }//GEN-LAST:event_addInsurance_Tax_TextFieldFocusLost

    private void addInsurance_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInsurance_Cancel_ButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_addInsurance_Cancel_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInsuranceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInsuranceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInsuranceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInsuranceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddInsuranceJFrame().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel jLabel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addInsurance_Brand_TextField;
    private javax.swing.JButton addInsurance_Cancel_Button;
    private javax.swing.JButton addInsurance_ChooseCustomer_Button;
    private javax.swing.JTextField addInsurance_CustomerName_TextField;
    private javax.swing.JTextField addInsurance_Date_TextField;
    private javax.swing.JTextField addInsurance_Money_TextField;
    private javax.swing.JTextField addInsurance_Number_TextField;
    private javax.swing.JButton addInsurance_OK_Button;
    private javax.swing.JTextField addInsurance_PlantNumber_TextField;
    private javax.swing.JTextArea addInsurance_Remark_TextArea;
    private javax.swing.JTextField addInsurance_StartDate_TextField;
    private javax.swing.JTextField addInsurance_Sum_TextField;
    private javax.swing.JTextField addInsurance_Tax_TextField;
    private javax.swing.JTextField addInsurance_Type_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
