/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.insuranceJFrame;

import Dao.GoodsDao;
import Dao.InsuranceDao;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 健鑫
 */
public class FindInsuranceJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FindInsuranceJFrame
     */
    public FindInsuranceJFrame() {
        initComponents();
    }
    private JTable jTable;
    private JLabel jLabel;
    public FindInsuranceJFrame(JTable jt,JLabel jl) {
        jTable=jt;
        jLabel=jl;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        findInsuranceDataTextField = new javax.swing.JTextField();
        findInsuranceBrandTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        findInsuranceCustomerTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        findInsuranceCarTextField = new javax.swing.JTextField();
        findInsurance_OKButton = new javax.swing.JButton();
        findInsurance_CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("查找条件");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("生效日早于：");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("保险公司：");

        findInsuranceDataTextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        findInsuranceBrandTextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("被保险人：");

        findInsuranceCustomerTextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("车牌号：");

        findInsuranceCarTextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        findInsurance_OKButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        findInsurance_OKButton.setText("确定");
        findInsurance_OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findInsurance_OKButtonActionPerformed(evt);
            }
        });

        findInsurance_CancelButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        findInsurance_CancelButton.setText("取消");
        findInsurance_CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findInsurance_CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(findInsurance_OKButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findInsuranceDataTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(findInsuranceBrandTextField)
                            .addComponent(findInsuranceCustomerTextField)
                            .addComponent(findInsuranceCarTextField))
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findInsurance_CancelButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(findInsuranceDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(findInsuranceBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(findInsuranceCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(findInsuranceCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findInsurance_OKButton)
                    .addComponent(findInsurance_CancelButton))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findInsurance_OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findInsurance_OKButtonActionPerformed
        // TODO add your handling code here:
        //获取table的model
        DefaultTableModel tableModel = (DefaultTableModel)jTable.getModel();
        //声明list
        ArrayList list=new ArrayList();
        //声明map
        Map rowDataMap=new HashMap();
        //声明dao
        InsuranceDao insuranceDao=new InsuranceDao();
        //获取对话框内容
        String dateString=findInsuranceDataTextField.getText();
        String brandString=findInsuranceBrandTextField.getText();
        String nameString=findInsuranceCustomerTextField.getText();
        String numberString=findInsuranceCarTextField.getText();
        //查询
        list=insuranceDao.list(-1,dateString, brandString, nameString, numberString);
        //没有查到结果时报错
        if(list==null){
             JOptionPane.showMessageDialog(null, "没有找到查询结果", "查询失败", JOptionPane.ERROR_MESSAGE); 
        }else{
            //计数器，记录第几行
            int i=0;
            //迭代器
            Iterator it1 = list.iterator();
            //重置table内容，避免第二次查询结果少于第一次时，第一次的内容依然存在
            tableModel.setRowCount(list.size());
            //遍历
            while(it1.hasNext()){
                rowDataMap=(Map) it1.next();
                //显示
//`i_paper_ID`, `i_car_ID`, `i_customer_ID`, `i_type`, `i_Tax`, `i_money`, `i_sum`, `i_start_date`, 
//`i_brand`, `i_car_number`, `i_customer_name`, `i_date``i_remark`
                tableModel.setValueAt(rowDataMap.get("i_id"), i,0);
                tableModel.setValueAt(rowDataMap.get("i_paper_ID"), i, 1);
                tableModel.setValueAt(rowDataMap.get("i_car_number"), i, 2);
                tableModel.setValueAt(rowDataMap.get("i_customer_name"), i, 3);
                tableModel.setValueAt(rowDataMap.get("i_type"), i, 4);
                tableModel.setValueAt(rowDataMap.get("i_brand"), i, 5);
                tableModel.setValueAt(rowDataMap.get("i_sum"), i, 6);
                tableModel.setValueAt(rowDataMap.get("i_start_date"), i, 7);
                tableModel.setValueAt(rowDataMap.get("i_date"), i, 8);
                tableModel.setValueAt(rowDataMap.get("i_remark"), i, 9);
                
                i++;
            } 
            //显示条目数量
            jLabel.setText(String.valueOf(i));
        }
        
     //关闭
        dispose();
    }//GEN-LAST:event_findInsurance_OKButtonActionPerformed

    private void findInsurance_CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findInsurance_CancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_findInsurance_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindInsuranceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindInsuranceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindInsuranceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindInsuranceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindInsuranceJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField findInsuranceBrandTextField;
    private javax.swing.JTextField findInsuranceCarTextField;
    private javax.swing.JTextField findInsuranceCustomerTextField;
    private javax.swing.JTextField findInsuranceDataTextField;
    private javax.swing.JButton findInsurance_CancelButton;
    private javax.swing.JButton findInsurance_OKButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
