/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.insuranceJFrame;

import Po.Insurance;

/**
 *
 * @author 健鑫
 */
public class InsuranceDetailInfromationJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddInsuranceJFrame
     */
    public InsuranceDetailInfromationJFrame() {
        initComponents();
    }
    private Insurance insurance=new Insurance();
    public InsuranceDetailInfromationJFrame(Insurance i) {
        insurance=i;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        insuranceDetail_Number_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        insuranceDetail_PlantNumber_TextField = new javax.swing.JTextField();
        insuranceDetail_CustomerName_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insuranceDetail_Brand_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        insuranceDetail_Type_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        insuranceDetail_Money_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        insuranceDetail_Tax_TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        insuranceDetail_Sum_TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        insuranceDetail_StartDate_TextField = new javax.swing.JTextField();
        InsuranceDetail_OK_Button = new javax.swing.JButton();
        insuranceDetail_Cancel_Button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        insuranceDetail_Remark_TextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        insuranceDetail_Date_TextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("详细信息");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("保单号：");

        insuranceDetail_Number_TextField.setEditable(false);
        insuranceDetail_Number_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_Number_TextField.setText(insurance.getI_Paper_ID());

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("车牌号：");

        insuranceDetail_PlantNumber_TextField.setEditable(false);
        insuranceDetail_PlantNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_PlantNumber_TextField.setText(insurance.getI_Car_Number());

        insuranceDetail_CustomerName_TextField.setEditable(false);
        insuranceDetail_CustomerName_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_CustomerName_TextField.setText(insurance.getI_Customer_Name());

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("保险公司：");

        insuranceDetail_Brand_TextField.setEditable(false);
        insuranceDetail_Brand_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_Brand_TextField.setText(insurance.getI_Brand());

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("保险类型：");

        insuranceDetail_Type_TextField.setEditable(false);
        insuranceDetail_Type_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_Type_TextField.setText(insurance.getI_Type());

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("保费：");

        insuranceDetail_Money_TextField.setEditable(false);
        insuranceDetail_Money_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_Money_TextField.setText(String.valueOf(insurance.getI_Money())
        );

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("税：");

        insuranceDetail_Tax_TextField.setEditable(false);
        insuranceDetail_Tax_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_Tax_TextField.setText(String.valueOf(insurance.getI_Tax())
        );

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("总价：");

        insuranceDetail_Sum_TextField.setEditable(false);
        insuranceDetail_Sum_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_Sum_TextField.setText(String.valueOf(insurance.getI_Sum()));

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel8.setText("保单生效时间：");

        insuranceDetail_StartDate_TextField.setEditable(false);
        insuranceDetail_StartDate_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_StartDate_TextField.setText(String.valueOf(insurance.getI_Start_Date())
        );

        InsuranceDetail_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        InsuranceDetail_OK_Button.setText("确定");
        InsuranceDetail_OK_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsuranceDetail_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsuranceDetail_OK_ButtonActionPerformed(evt);
            }
        });

        insuranceDetail_Cancel_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_Cancel_Button.setText("取消");
        insuranceDetail_Cancel_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insuranceDetail_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceDetail_Cancel_ButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel9.setText("备注");

        insuranceDetail_Remark_TextArea.setEditable(false);
        insuranceDetail_Remark_TextArea.setColumns(20);
        insuranceDetail_Remark_TextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        insuranceDetail_Remark_TextArea.setRows(5);
        insuranceDetail_Remark_TextArea.setText(insurance.getI_Remark());
        jScrollPane1.setViewportView(insuranceDetail_Remark_TextArea);

        jLabel10.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel10.setText("投保时间：");

        insuranceDetail_Date_TextField.setEditable(false);
        insuranceDetail_Date_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        insuranceDetail_Date_TextField.setText(String.valueOf(insurance.getI_Date())
        );

        jLabel11.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel11.setText("被保险人：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(InsuranceDetail_OK_Button))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insuranceDetail_StartDate_TextField)
                            .addComponent(insuranceDetail_Brand_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insuranceDetail_Type_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insuranceDetail_Sum_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insuranceDetail_Tax_TextField)
                            .addComponent(insuranceDetail_Money_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insuranceDetail_Cancel_Button)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(insuranceDetail_Date_TextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insuranceDetail_CustomerName_TextField)
                            .addComponent(insuranceDetail_Number_TextField)
                            .addComponent(insuranceDetail_PlantNumber_TextField))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceDetail_CustomerName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(insuranceDetail_PlantNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(insuranceDetail_Number_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(insuranceDetail_Brand_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(insuranceDetail_Type_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(insuranceDetail_Money_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(insuranceDetail_Tax_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(insuranceDetail_Sum_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(insuranceDetail_StartDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(insuranceDetail_Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsuranceDetail_OK_Button)
                    .addComponent(insuranceDetail_Cancel_Button))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsuranceDetail_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsuranceDetail_OK_ButtonActionPerformed
       dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_InsuranceDetail_OK_ButtonActionPerformed

    private void insuranceDetail_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceDetail_Cancel_ButtonActionPerformed
       dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_insuranceDetail_Cancel_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsuranceDetailInfromationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsuranceDetailInfromationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsuranceDetailInfromationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsuranceDetailInfromationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsuranceDetailInfromationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsuranceDetail_OK_Button;
    private javax.swing.JTextField insuranceDetail_Brand_TextField;
    private javax.swing.JButton insuranceDetail_Cancel_Button;
    private javax.swing.JTextField insuranceDetail_CustomerName_TextField;
    private javax.swing.JTextField insuranceDetail_Date_TextField;
    private javax.swing.JTextField insuranceDetail_Money_TextField;
    private javax.swing.JTextField insuranceDetail_Number_TextField;
    private javax.swing.JTextField insuranceDetail_PlantNumber_TextField;
    private javax.swing.JTextArea insuranceDetail_Remark_TextArea;
    private javax.swing.JTextField insuranceDetail_StartDate_TextField;
    private javax.swing.JTextField insuranceDetail_Sum_TextField;
    private javax.swing.JTextField insuranceDetail_Tax_TextField;
    private javax.swing.JTextField insuranceDetail_Type_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
