/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.goodsJFrame;

import Po.Goods;

/**
 *
 * @author 健鑫
 */
public class DetailInformateionGoodsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DetailInformateionGoodsJFrame
     */
    private Goods goods;
    public DetailInformateionGoodsJFrame() {
        initComponents();
    }
    public DetailInformateionGoodsJFrame(Goods gds){
        goods=gds;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GoodsDetaile_Remark_TextArea = new javax.swing.JTextArea();
        GoodsDetaile_Name_TextField = new javax.swing.JTextField();
        GoodsDetaile_Brand_TextField = new javax.swing.JTextField();
        GoodsDetaile_Type_TextField = new javax.swing.JTextField();
        GoodsDetaile_Number_TextField = new javax.swing.JTextField();
        GoodsDetaile_Price_TextField = new javax.swing.JTextField();
        GoodsDetaile_Cancel_Button = new javax.swing.JButton();
        GoodsDetail_OK_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("详细信息");
        setLocation(new java.awt.Point(400, 200));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(550, 800));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("商品名：");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("品牌：");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("计费方式：");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("备注：");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("库存量：");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("价格：");

        GoodsDetaile_Remark_TextArea.setColumns(20);
        GoodsDetaile_Remark_TextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        GoodsDetaile_Remark_TextArea.setRows(5);
        GoodsDetaile_Remark_TextArea.setText(goods.getG_Remark());
        jScrollPane1.setViewportView(GoodsDetaile_Remark_TextArea);

        GoodsDetaile_Name_TextField.setEditable(false);
        GoodsDetaile_Name_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        GoodsDetaile_Name_TextField.setText(goods.getG_Name());

        GoodsDetaile_Brand_TextField.setEditable(false);
        GoodsDetaile_Brand_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        GoodsDetaile_Brand_TextField.setText(goods.getG_Brand());

        GoodsDetaile_Type_TextField.setEditable(false);
        GoodsDetaile_Type_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        GoodsDetaile_Type_TextField.setText(goods.getG_Pricingway()
        );

        GoodsDetaile_Number_TextField.setEditable(false);
        GoodsDetaile_Number_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        GoodsDetaile_Number_TextField.setText(String.valueOf(goods.getG_Inventory()));

        GoodsDetaile_Price_TextField.setEditable(false);
        GoodsDetaile_Price_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        GoodsDetaile_Price_TextField.setText(String.valueOf(goods.getG_Price()));

        GoodsDetaile_Cancel_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        GoodsDetaile_Cancel_Button.setText("取消");
        GoodsDetaile_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodsDetaile_Cancel_ButtonActionPerformed(evt);
            }
        });

        GoodsDetail_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        GoodsDetail_OK_Button.setText("确定");
        GoodsDetail_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodsDetail_OK_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(GoodsDetaile_Name_TextField)
                    .addComponent(GoodsDetaile_Brand_TextField)
                    .addComponent(GoodsDetaile_Type_TextField)
                    .addComponent(GoodsDetaile_Number_TextField)
                    .addComponent(GoodsDetaile_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GoodsDetail_OK_Button)
                .addGap(83, 83, 83)
                .addComponent(GoodsDetaile_Cancel_Button)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(GoodsDetaile_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GoodsDetaile_Brand_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GoodsDetaile_Type_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(GoodsDetaile_Number_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(GoodsDetaile_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoodsDetaile_Cancel_Button)
                            .addComponent(GoodsDetail_OK_Button)))
                    .addComponent(jLabel4))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoodsDetail_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodsDetail_OK_ButtonActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_GoodsDetail_OK_ButtonActionPerformed

    private void GoodsDetaile_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodsDetaile_Cancel_ButtonActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_GoodsDetaile_Cancel_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailInformateionGoodsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailInformateionGoodsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailInformateionGoodsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailInformateionGoodsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DetailInformateionGoodsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoodsDetail_OK_Button;
    private javax.swing.JTextField GoodsDetaile_Brand_TextField;
    private javax.swing.JButton GoodsDetaile_Cancel_Button;
    private javax.swing.JTextField GoodsDetaile_Name_TextField;
    private javax.swing.JTextField GoodsDetaile_Number_TextField;
    private javax.swing.JTextField GoodsDetaile_Price_TextField;
    private javax.swing.JTextArea GoodsDetaile_Remark_TextArea;
    private javax.swing.JTextField GoodsDetaile_Type_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
