package Po;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : customermanager
//  @ File Name : Customer.java
//  @ Date : 2017/7/9
//  @ Author : 宋健鑫
//
//




public class Customer {
	private String c_Card_Number;//身份证号
	private int c_ID;
	private String c_Name;//姓名
	private String c_Tell;//电话
	private float c_Integration;//积分
	private String c_Sex;//性别
	private String c_Address;//住址
	private float c_Cash;//押金
        private String c_Remark;//备注

    public String getC_Card_Number() {
        return c_Card_Number;
    }

    public void setC_Card_Number(String c_Card_Number) {
        this.c_Card_Number = c_Card_Number;
    }

    public int getC_ID() {
        return c_ID;
    }

    public void setC_ID(int c_ID) {
        this.c_ID = c_ID;
    }

    public String getC_Name() {
        return c_Name;
    }

    public void setC_Name(String c_Name) {
        this.c_Name = c_Name;
    }

    public String getC_Tell() {
        return c_Tell;
    }

    public void setC_Tell(String c_Tell) {
        this.c_Tell = c_Tell;
    }

    public float getC_Integration() {
        return c_Integration;
    }

    public void setC_Integration(float c_Integration) {
        this.c_Integration = c_Integration;
    }

    public String getC_Sex() {
        return c_Sex;
    }

    public void setC_Sex(String c_Sex) {
        this.c_Sex = c_Sex;
    }

    public String getC_Address() {
        return c_Address;
    }

    public void setC_Address(String c_Address) {
        this.c_Address = c_Address;
    }

    public float getC_Cash() {
        return c_Cash;
    }

    public void setC_Cash(float c_Cash) {
        this.c_Cash = c_Cash;
    }

    public String getC_Remark() {
        return c_Remark;
    }

    public void setC_Remark(String c_Remark) {
        this.c_Remark = c_Remark;
    }
	
}
