package Po;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : customermanager
//  @ File Name : Goods.java
//  @ Date : 2017/7/9
//  @ Author : 宋健鑫
//
//




public class Goods {
	private int g_ID;
        private String g_Brand;//品牌
	private String g_Name;//商品名
	private String g_Pricingway;//计费方式
	private float g_Inventory;//库存量
	private float g_Price;//价格
	private String g_Remark;//备注

    public int getG_ID() {
        return g_ID;
    }

    public void setG_ID(int g_ID) {
        this.g_ID = g_ID;
    }

    public String getG_Brand() {
        return g_Brand;
    }

    public void setG_Brand(String g_Brand) {
        this.g_Brand = g_Brand;
    }

    public String getG_Name() {
        return g_Name;
    }

    public void setG_Name(String g_Name) {
        this.g_Name = g_Name;
    }

    public String getG_Pricingway() {
        return g_Pricingway;
    }

    public void setG_Pricingway(String g_Pricingway) {
        this.g_Pricingway = g_Pricingway;
    }

    public float getG_Inventory() {
        return g_Inventory;
    }

    public void setG_Inventory(float g_Inventory) {
        this.g_Inventory = g_Inventory;
    }

    public float getG_Price() {
        return g_Price;
    }

    public void setG_Price(float g_Price) {
        this.g_Price = g_Price;
    }

    public String getG_Remark() {
        return g_Remark;
    }

    public void setG_Remark(String g_Remark) {
        this.g_Remark = g_Remark;
    }
	
}
