package Po;
import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : customermanager
//  @ File Name : SailList.java
//  @ Date : 2017/7/9
//  @ Author : 宋健鑫
//
//




public class SailList {
	private int s_ID;
	private int s_Customer_ID;//客户id
	private String s_Buy_Or_Return;//退货或销售
	private int s_Goods_ID;//商品id
	private Date s_Date_Time;//出售日期
	private float s_Number;//出售数量
	private String s_Remark;//备注
	private String s_Customer_Name;//客户姓名
	private String s_Goods_Name;//商品名

    public int getS_ID() {
        return s_ID;
    }

    public void setS_ID(int s_ID) {
        this.s_ID = s_ID;
    }

    public int getS_Customer_ID() {
        return s_Customer_ID;
    }

    public void setS_Customer_ID(int s_Customer_ID) {
        this.s_Customer_ID = s_Customer_ID;
    }

    public String getS_Buy_Or_Return() {
        return s_Buy_Or_Return;
    }

    public void setS_Buy_Or_Return(String s_Buy_Or_Return) {
        this.s_Buy_Or_Return = s_Buy_Or_Return;
    }

    public int getS_Goods_ID() {
        return s_Goods_ID;
    }

    public void setS_Goods_ID(int s_Goods_ID) {
        this.s_Goods_ID = s_Goods_ID;
    }

    public Date getS_Date_Time() {
        return s_Date_Time;
    }

    public void setS_Date_Time(Date s_Date_Time) {
        this.s_Date_Time = s_Date_Time;
    }

    public float getS_Number() {
        return s_Number;
    }

    public void setS_Number(float s_Number) {
        this.s_Number = s_Number;
    }

    public String getS_Remark() {
        return s_Remark;
    }

    public void setS_Remark(String s_Remark) {
        this.s_Remark = s_Remark;
    }

    public String getS_Customer_Name() {
        return s_Customer_Name;
    }

    public void setS_Customer_Name(String s_Customer_Name) {
        this.s_Customer_Name = s_Customer_Name;
    }

    public String getS_Goods_Name() {
        return s_Goods_Name;
    }

    public void setS_Goods_Name(String s_Goods_Name) {
        this.s_Goods_Name = s_Goods_Name;
    }
}
