package Po;
import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : customermanager
//  @ File Name : Vehicle.java
//  @ Date : 2017/7/9
//  @ Author : 宋健鑫
//
//




public class Vehicle {
	private String v_Plante_Nomber;//车牌号
	private int v_ID;
	private int v_Owner_ID;//车辆拥有人id
	private Date v_Register_Date;//注册日期
	private Date v_Give_Date;//发证日期
	private String v_Engine_Nomber;//发动机号
	private String v_VIN;//VIN号
	private String v_Model;//品牌
	private String v_User_Character;//使用性质
	private String v_Vehicle_Type;//车辆类型
	private String v_Remark;//备注
	private String v_Owner_Name;//车辆拥有人姓名
        

    public String getV_Plante_Nomber() {
        return v_Plante_Nomber;
    }

    public void setV_Plante_Nomber(String v_Plante_Nomber) {
        this.v_Plante_Nomber = v_Plante_Nomber;
    }

    public int getV_ID() {
        return v_ID;
    }

    public void setV_ID(int v_ID) {
        this.v_ID = v_ID;
    }

    public int getV_Owner_ID() {
        return v_Owner_ID;
    }

    public void setV_Owner_ID(int v_Owner_ID) {
        this.v_Owner_ID = v_Owner_ID;
    }

    public Date getV_Register_Date() {
        return v_Register_Date;
    }

    public void setV_Register_Date(Date v_Register_Date) {
        this.v_Register_Date = v_Register_Date;
    }

    public Date getV_Give_Date() {
        return v_Give_Date;
    }

    public void setV_Give_Date(Date v_Give_Date) {
        this.v_Give_Date = v_Give_Date;
    }

    public String getV_Engine_Nomber() {
        return v_Engine_Nomber;
    }

    public void setV_Engine_Nomber(String v_Engine_Nomber) {
        this.v_Engine_Nomber = v_Engine_Nomber;
    }

    public String getV_VIN() {
        return v_VIN;
    }

    public void setV_VIN(String v_VIN) {
        this.v_VIN = v_VIN;
    }

    public String getV_Model() {
        return v_Model;
    }

    public void setV_Model(String v_Model) {
        this.v_Model = v_Model;
    }

    public String getV_User_Character() {
        return v_User_Character;
    }

    public void setV_User_Character(String v_User_Character) {
        this.v_User_Character = v_User_Character;
    }

    public String getV_Vehicle_Type() {
        return v_Vehicle_Type;
    }

    public void setV_Vehicle_Type(String v_Vehicle_Type) {
        this.v_Vehicle_Type = v_Vehicle_Type;
    }

    public String getV_Remark() {
        return v_Remark;
    }

    public void setV_Remark(String v_Remark) {
        this.v_Remark = v_Remark;
    }

    public String getV_Owner_Name() {
        return v_Owner_Name;
    }

    public void setV_Owner_Name(String v_Owner_Name) {
        this.v_Owner_Name = v_Owner_Name;
    }
}
