/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.List;

import Dao.BuyListDao;
import Dao.SailListDao;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 健鑫
 */
public class SailFindJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BuyFindJFrame
     */
    public SailFindJFrame() {
        initComponents();
    }
    //主界面显示
    private JTable jTable;
    //主机面传值
    private JLabel jLabel;
    public SailFindJFrame(JTable jt,JLabel jl) {
        jTable=jt;
        jLabel=jl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sailFind_Name_TextField = new javax.swing.JTextField();
        sailFind_StartDate_TextField = new javax.swing.JTextField();
        sailFind_EndDate_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sailFind_OK_Button = new javax.swing.JButton();
        sailFind_Cancel_Button = new javax.swing.JButton();
        sailFind_CustomerName_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sail_ReturnORBuy_ComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        sailFind_Name_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        sailFind_StartDate_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        sailFind_EndDate_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("至");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("商品名：");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("时间区间：");

        sailFind_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sailFind_OK_Button.setText("确定");
        sailFind_OK_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sailFind_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sailFind_OK_ButtonActionPerformed(evt);
            }
        });

        sailFind_Cancel_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sailFind_Cancel_Button.setText("取消");
        sailFind_Cancel_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sailFind_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sailFind_Cancel_ButtonActionPerformed(evt);
            }
        });

        sailFind_CustomerName_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("退货or购买");

        sail_ReturnORBuy_ComboBox.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sail_ReturnORBuy_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "出售", "退货" }));

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("客户姓名:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(sailFind_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sailFind_StartDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sailFind_EndDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sailFind_OK_Button)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(sailFind_Cancel_Button))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sail_ReturnORBuy_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sailFind_CustomerName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sailFind_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addComponent(sailFind_StartDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addComponent(sailFind_EndDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sail_ReturnORBuy_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sailFind_CustomerName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sailFind_OK_Button)
                    .addComponent(sailFind_Cancel_Button))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sailFind_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sailFind_OK_ButtonActionPerformed
        // TODO add your handling code here:
        //获取tabl的model
        DefaultTableModel tableModel = (DefaultTableModel)jTable.getModel();
       //声明list
        ArrayList list=new ArrayList();
        //声明map
        Map rowDataMap=new HashMap();
        //声明dao
        SailListDao sailListDao=new SailListDao();
        //获取对话框内数据
        String nameString=sailFind_Name_TextField.getText();
        String begintimeString=sailFind_StartDate_TextField.getText();
        String endtimeString=sailFind_EndDate_TextField.getText();
        String customerString=sailFind_CustomerName_TextField.getText();
        String buyorreturnString=(String) sail_ReturnORBuy_ComboBox.getSelectedItem();
        //获得查询结果
        //System.out.println("JFrame.List.BuyFindJFrame.buyFind_OK_ButtonActionPerformed()");
        list=sailListDao.list(begintimeString, endtimeString, nameString,customerString,buyorreturnString);
        //判断空值
        if(list==null){
             JOptionPane.showMessageDialog(null, "没有找到查询结果", "查询失败", JOptionPane.ERROR_MESSAGE); 
        }else{
            //计数，第几行显示
            int i=0;
            //迭代器
            Iterator it1 = list.iterator();
            //重置table内容，避免第二次查询结果少于第一次时，第一次的内容依然存在
            tableModel.setRowCount(list.size());
            //遍历
            while(it1.hasNext()){
                
                rowDataMap=(Map) it1.next();
 //  s_customer_id`, `s_goods_id`, `s_buy_or_return`, `s_data_time`, `s_number`,
//`s_remark`, `s_customer_name`, `s_goods_name`
                //显示
                tableModel.setValueAt(rowDataMap.get("s_id"), i,0);
                //tableModel.setValueAt(1, i,0);
                tableModel.setValueAt(rowDataMap.get("s_goods_name"), i, 1);
                tableModel.setValueAt(rowDataMap.get("s_customer_name"), i, 2);
                tableModel.setValueAt(rowDataMap.get("s_buy_or_return"), i, 3);
                tableModel.setValueAt(rowDataMap.get("s_data_time"), i, 4);
                tableModel.setValueAt(rowDataMap.get("s_number"), i, 5);
                tableModel.setValueAt(rowDataMap.get("s_remark"), i, 6);
                
                i++;
            } 
            //显示条目数量
            jLabel.setText(String.valueOf(i));
        }
        
        //关闭
        dispose();
    }//GEN-LAST:event_sailFind_OK_ButtonActionPerformed

    private void sailFind_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sailFind_Cancel_ButtonActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_sailFind_Cancel_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SailFindJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SailFindJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SailFindJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SailFindJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SailFindJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton sailFind_Cancel_Button;
    private javax.swing.JTextField sailFind_CustomerName_TextField;
    private javax.swing.JTextField sailFind_EndDate_TextField;
    private javax.swing.JTextField sailFind_Name_TextField;
    private javax.swing.JButton sailFind_OK_Button;
    private javax.swing.JTextField sailFind_StartDate_TextField;
    private javax.swing.JComboBox<String> sail_ReturnORBuy_ComboBox;
    // End of variables declaration//GEN-END:variables
}
