/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.List;

import Dao.CustomerDao;
import Dao.GoodsDao;
import JFrame.customJFrame.CustomerDetailInformationJFrame;
import JFrame.goodsJFrame.DetailInformateionGoodsJFrame;
import Po.Goods;
import Po.SailList;

/**
 *
 * @author 健鑫
 */
public class SailDetailInformationJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SailDetailInformationJFrame
     */
    public SailDetailInformationJFrame() {
        initComponents();
    }
    private SailList sailList;
    private int goodsid;
    private int customerid;
    public SailDetailInformationJFrame(SailList sl){
        sailList=sl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sail_CustomerName_TextField = new javax.swing.JTextField();
        sail_Name_TextField = new javax.swing.JTextField();
        sail_Date_TextField = new javax.swing.JTextField();
        sail_Number_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sail_Remark_TextArea = new javax.swing.JTextArea();
        sailDetail_OK_Button = new javax.swing.JButton();
        sailDetail_Name_Button = new javax.swing.JButton();
        sailDetail_CustonmerName_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sail_ReturnORBuy_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("销售时间：");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("销售数量：");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("备注：");

        sail_CustomerName_TextField.setEditable(false);
        sail_CustomerName_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sail_CustomerName_TextField.setText(sailList.getS_Customer_Name());

        sail_Name_TextField.setEditable(false);
        sail_Name_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sail_Name_TextField.setText(sailList.getS_Goods_Name());

        sail_Date_TextField.setEditable(false);
        sail_Date_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sail_Date_TextField.setText(String.valueOf(sailList.getS_Date_Time()));

        sail_Number_TextField.setEditable(false);
        sail_Number_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sail_Number_TextField.setText(String.valueOf(sailList.getS_Number())
        );

        sail_Remark_TextArea.setEditable(false);
        sail_Remark_TextArea.setColumns(20);
        sail_Remark_TextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        sail_Remark_TextArea.setRows(5);
        sail_Remark_TextArea.setText(sailList.getS_Remark());
        jScrollPane1.setViewportView(sail_Remark_TextArea);

        sailDetail_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sailDetail_OK_Button.setText("确定");
        sailDetail_OK_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sailDetail_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sailDetail_OK_ButtonActionPerformed(evt);
            }
        });

        sailDetail_Name_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sailDetail_Name_Button.setText("商品名：");
        sailDetail_Name_Button.setContentAreaFilled(false);
        sailDetail_Name_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sailDetail_Name_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sailDetail_Name_ButtonActionPerformed(evt);
            }
        });

        sailDetail_CustonmerName_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sailDetail_CustonmerName_Button.setText("购买者姓名：");
        sailDetail_CustonmerName_Button.setContentAreaFilled(false);
        sailDetail_CustonmerName_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sailDetail_CustonmerName_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sailDetail_CustonmerName_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("退货or购买");

        sail_ReturnORBuy_TextField.setEditable(false);
        sail_ReturnORBuy_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        sail_ReturnORBuy_TextField.setText(sailList.getS_Buy_Or_Return());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sailDetail_Name_Button)
                            .addComponent(sailDetail_CustonmerName_Button))))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sail_CustomerName_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(sail_Date_TextField)
                    .addComponent(sail_Name_TextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(sailDetail_OK_Button)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(sail_Number_TextField)
                                    .addComponent(sail_ReturnORBuy_TextField))
                                .addContainerGap(83, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sail_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sailDetail_Name_Button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sail_CustomerName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sailDetail_CustonmerName_Button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sail_Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sail_Number_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sail_ReturnORBuy_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(sailDetail_OK_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sailDetail_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sailDetail_OK_ButtonActionPerformed
        //exit
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_sailDetail_OK_ButtonActionPerformed

    private void sailDetail_Name_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sailDetail_Name_ButtonActionPerformed
        
        new DetailInformateionGoodsJFrame(new GoodsDao().find(sailList.getS_Goods_ID())).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_sailDetail_Name_ButtonActionPerformed

    private void sailDetail_CustonmerName_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sailDetail_CustonmerName_ButtonActionPerformed
        new CustomerDetailInformationJFrame(new CustomerDao().find(sailList.getS_Customer_ID())).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_sailDetail_CustonmerName_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SailDetailInformationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SailDetailInformationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SailDetailInformationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SailDetailInformationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SailDetailInformationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sailDetail_CustonmerName_Button;
    private javax.swing.JButton sailDetail_Name_Button;
    private javax.swing.JButton sailDetail_OK_Button;
    private javax.swing.JTextField sail_CustomerName_TextField;
    private javax.swing.JTextField sail_Date_TextField;
    private javax.swing.JTextField sail_Name_TextField;
    private javax.swing.JTextField sail_Number_TextField;
    private javax.swing.JTextArea sail_Remark_TextArea;
    private javax.swing.JTextField sail_ReturnORBuy_TextField;
    // End of variables declaration//GEN-END:variables
}
