/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customermanager;

import JFrame.List.BuyJFrame;
import JFrame.List.SailJFrame;
import JFrame.carJFrame.CarJFrame;
import JFrame.customJFrame.CustomerJFrame;
import JFrame.goodsJFrame.GoodsJFrame;
import JFrame.help.AboutJFrame;
import JFrame.insuranceJFrame.InsuranceJFrame;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 健鑫
 */
public class WelcomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public WelcomeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerList_Button = new javax.swing.JButton();
        carList_Button = new javax.swing.JButton();
        insuranceList_Button = new javax.swing.JButton();
        goodsList_Button = new javax.swing.JButton();
        welcome_userhelp_Button = new javax.swing.JButton();
        welcome_About_Button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("客户管理系统\n");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("欢迎使用");

        jLabel3.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        jLabel3.setText("客户管理系统");

        customerList_Button.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        customerList_Button.setText("客户列表");
        customerList_Button.setToolTipText("显示客户列表并且对客户执行各种操作");
        customerList_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerList_ButtonActionPerformed(evt);
            }
        });

        carList_Button.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        carList_Button.setText("车辆列表");
        carList_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carList_ButtonActionPerformed(evt);
            }
        });

        insuranceList_Button.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        insuranceList_Button.setText("保险列表");
        insuranceList_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insuranceList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceList_ButtonActionPerformed(evt);
            }
        });

        goodsList_Button.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        goodsList_Button.setText("商品列表");
        goodsList_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goodsList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodsList_ButtonActionPerformed(evt);
            }
        });

        welcome_userhelp_Button.setText("使用说明");
        welcome_userhelp_Button.setToolTipText("本系统的使用说明书");
        welcome_userhelp_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        welcome_userhelp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcome_userhelp_ButtonActionPerformed(evt);
            }
        });

        welcome_About_Button.setText("关于");
        welcome_About_Button.setToolTipText("软件声明");
        welcome_About_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        welcome_About_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcome_About_ButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        jButton1.setText("进货记录");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        jButton2.setText("销售记录");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerList_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insuranceList_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(welcome_userhelp_Button, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(goodsList_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(carList_Button, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(welcome_About_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerList_Button)
                    .addComponent(carList_Button))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceList_Button)
                    .addComponent(goodsList_Button))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcome_userhelp_Button)
                    .addComponent(welcome_About_Button))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //保险列表
    private void insuranceList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceList_ButtonActionPerformed
        InsuranceJFrame insuranceJFrame = new InsuranceJFrame();
        insuranceJFrame.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_insuranceList_ButtonActionPerformed
    //客户列表
    private void customerList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerList_ButtonActionPerformed
        CustomerJFrame customerJFrame=new CustomerJFrame();
        customerJFrame.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_customerList_ButtonActionPerformed
    //车辆列表
    private void carList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carList_ButtonActionPerformed
        CarJFrame carJFrame = new CarJFrame();
        carJFrame.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_carList_ButtonActionPerformed
    //商品列表
    private void goodsList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodsList_ButtonActionPerformed
        GoodsJFrame goodsJFrame = new GoodsJFrame();
        goodsJFrame.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_goodsList_ButtonActionPerformed
    //关于软件
    private void welcome_About_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcome_About_ButtonActionPerformed
        new AboutJFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_welcome_About_ButtonActionPerformed
    //进货列表
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new BuyJFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    //销售列表
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new SailJFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    //使用说明
    private void welcome_userhelp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcome_userhelp_ButtonActionPerformed
 
        try {
            java.awt.Desktop.getDesktop().open(new File("帮助文档.CHM"));
        } catch (IOException ex) {
            Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_welcome_userhelp_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carList_Button;
    private javax.swing.JButton customerList_Button;
    private javax.swing.JButton goodsList_Button;
    private javax.swing.JButton insuranceList_Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton welcome_About_Button;
    private javax.swing.JButton welcome_userhelp_Button;
    // End of variables declaration//GEN-END:variables
}
