/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.carJFrame;

import Dao.VehicleDao;
import JFrame.customJFrame.CustomerChooseJFrame;
import JFrame.insuranceJFrame.UpdateInsuranceJFrame;
import Po.Vehicle;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 健鑫
 */
public class AddCarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddCarJFrame
     */
    public AddCarJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addCar_PlantNumber_TextField = new javax.swing.JTextField();
        addCar_ChooseOwner_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addCar_Remark_TextArea = new javax.swing.JTextArea();
        addCar_GiveDate_TextField = new javax.swing.JTextField();
        addCar_EngineNumber_TextField = new javax.swing.JTextField();
        addCar_VIN_TextField = new javax.swing.JTextField();
        addCar_Model_TextField = new javax.swing.JTextField();
        addCar_UserCharacter_TextField = new javax.swing.JTextField();
        addCar_Type_TextField = new javax.swing.JTextField();
        addCar_RegistDate_TextField = new javax.swing.JTextField();
        addCar_OK_Button = new javax.swing.JButton();
        addCar_Cancel_Button = new javax.swing.JButton();
        addCar_OwnerName_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("新增车辆");

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("车牌号：");

        addCar_PlantNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addCar_ChooseOwner_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addCar_ChooseOwner_Button.setText("选择车主");
        addCar_ChooseOwner_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCar_ChooseOwner_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCar_ChooseOwner_ButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("注册日期：");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("发证日期：");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("发动机号：");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("识别代码：");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("品牌型号：");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("使用性质：");

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel8.setText("车辆类型：");

        jLabel9.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel9.setText("备注：");

        addCar_Remark_TextArea.setColumns(20);
        addCar_Remark_TextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        addCar_Remark_TextArea.setRows(5);
        jScrollPane1.setViewportView(addCar_Remark_TextArea);

        addCar_GiveDate_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addCar_EngineNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addCar_VIN_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addCar_Model_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addCar_UserCharacter_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addCar_Type_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addCar_RegistDate_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        addCar_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addCar_OK_Button.setText("确定");
        addCar_OK_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCar_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCar_OK_ButtonActionPerformed(evt);
            }
        });

        addCar_Cancel_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addCar_Cancel_Button.setText("取消");
        addCar_Cancel_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCar_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCar_Cancel_ButtonActionPerformed(evt);
            }
        });

        addCar_OwnerName_TextField.setEditable(false);
        addCar_OwnerName_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addCar_OK_Button)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addComponent(addCar_ChooseOwner_Button))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(addCar_PlantNumber_TextField)
                            .addComponent(addCar_GiveDate_TextField)
                            .addComponent(addCar_EngineNumber_TextField)
                            .addComponent(addCar_VIN_TextField)
                            .addComponent(addCar_Model_TextField)
                            .addComponent(addCar_UserCharacter_TextField)
                            .addComponent(addCar_Type_TextField)
                            .addComponent(addCar_RegistDate_TextField)
                            .addComponent(addCar_OwnerName_TextField))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCar_Cancel_Button)
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCar_ChooseOwner_Button)
                    .addComponent(addCar_OwnerName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addCar_PlantNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addCar_RegistDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addCar_GiveDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addCar_EngineNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addCar_VIN_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addCar_Model_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addCar_UserCharacter_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addCar_Type_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCar_OK_Button)
                    .addComponent(addCar_Cancel_Button))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCar_ChooseOwner_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCar_ChooseOwner_ButtonActionPerformed
        // TODO add your handling code here:
        jLable=new javax.swing.JLabel();
        new CustomerChooseJFrame(jLable, addCar_OwnerName_TextField).setVisible(true);
    }//GEN-LAST:event_addCar_ChooseOwner_ButtonActionPerformed

    private void addCar_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCar_Cancel_ButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_addCar_Cancel_ButtonActionPerformed

    private void addCar_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCar_OK_ButtonActionPerformed
        // TODO add your handling code here:
        Vehicle vehicle=new Vehicle();
        //设置data格式
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");  
        java.util.Date date=null;
        String dstr=null;
        
        vehicle.setV_Owner_Name(addCar_OwnerName_TextField.getText());
        vehicle.setV_Engine_Nomber(addCar_EngineNumber_TextField.getText());
        
        dstr=addCar_GiveDate_TextField.getText();
         try { 
            date=sdf.parse(dstr);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateInsuranceJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        vehicle.setV_Give_Date(date);
        dstr=addCar_RegistDate_TextField.getText();
         try { 
            date=sdf.parse(dstr);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateInsuranceJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        vehicle.setV_Register_Date(date);
        vehicle.setV_Model(addCar_Model_TextField.getText());
        vehicle.setV_Owner_ID(Integer.valueOf(jLable.getText()));
        vehicle.setV_Plante_Nomber(addCar_PlantNumber_TextField.getText());
        vehicle.setV_Remark(addCar_Remark_TextArea.getText());
        vehicle.setV_User_Character(addCar_UserCharacter_TextField.getText());
        vehicle.setV_VIN(addCar_VIN_TextField.getText());
        vehicle.setV_Vehicle_Type(addCar_Type_TextField.getText());
        new VehicleDao().add(vehicle);
        dispose();
    }//GEN-LAST:event_addCar_OK_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCarJFrame().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel jLable;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCar_Cancel_Button;
    private javax.swing.JButton addCar_ChooseOwner_Button;
    private javax.swing.JTextField addCar_EngineNumber_TextField;
    private javax.swing.JTextField addCar_GiveDate_TextField;
    private javax.swing.JTextField addCar_Model_TextField;
    private javax.swing.JButton addCar_OK_Button;
    private javax.swing.JTextField addCar_OwnerName_TextField;
    private javax.swing.JTextField addCar_PlantNumber_TextField;
    private javax.swing.JTextField addCar_RegistDate_TextField;
    private javax.swing.JTextArea addCar_Remark_TextArea;
    private javax.swing.JTextField addCar_Type_TextField;
    private javax.swing.JTextField addCar_UserCharacter_TextField;
    private javax.swing.JTextField addCar_VIN_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
