/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.carJFrame;

import Dao.GoodsDao;
import Dao.VehicleDao;
import JFrame.goodsJFrame.DetailInformateionGoodsJFrame;
import JFrame.help.AboutJFrame;
import JFrame.insuranceJFrame.AddInsuranceJFrame;
import Po.Goods;
import customermanager.WelcomeJFrame;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.JTableExportToExcel;

/**
 *
 * @author 健鑫
 */
public class CarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form car
     */
    public CarJFrame() {
        initComponents();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        //声明list
        ArrayList list = new ArrayList();
        //声明map
        Map rowDataMap = new HashMap();
        //查询
        list = new VehicleDao().list(-1, "", "", "", "");
        //没有查到结果时报错
        if (list == null) {
            JOptionPane.showMessageDialog(null, "没有找到查询结果", "查询失败", JOptionPane.ERROR_MESSAGE);
        } else {
            //计数器，记录第几行
            int i = 0;
            //迭代器
            Iterator it1 = list.iterator();
            //重置table内容，避免第二次查询结果少于第一次时，第一次的内容依然存在
            tableModel.setRowCount(list.size());
            //遍历
            while (it1.hasNext()) {
                rowDataMap = (Map) it1.next();
                //显示
//`V_owner_id`, `V_plante_nomber`, 
//`V_register_date`, `V_give_date`, `V_engine_nomber`, `V_VIN`, `V_model`, 
//`V_use_character`, `V_Vehicle_type`, `V_remark`,`V_owner_name`
                tableModel.setValueAt(rowDataMap.get("V_ID"), i, 0);
                tableModel.setValueAt(rowDataMap.get("V_plante_nomber"), i, 1);
                tableModel.setValueAt(rowDataMap.get("V_owner_name"), i, 2);
                tableModel.setValueAt(rowDataMap.get("V_register_date"), i, 3);
                tableModel.setValueAt(rowDataMap.get("V_give_date"), i, 4);
                tableModel.setValueAt(rowDataMap.get("V_engine_nomber"), i, 5);
                tableModel.setValueAt(rowDataMap.get("V_VIN"), i, 6);
                tableModel.setValueAt(rowDataMap.get("V_use_character"), i, 7);
                tableModel.setValueAt(rowDataMap.get("V_model"), i, 8);
                tableModel.setValueAt(rowDataMap.get("V_Vehicle_type"), i, 9);
                tableModel.setValueAt(rowDataMap.get("V_remark"), i, 10);

                i++;
            }
            //显示条目数量
            car_Number.setText(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar3 = new javax.swing.JToolBar();
        addCar_Button = new javax.swing.JButton();
        deleteCar_Button1 = new javax.swing.JButton();
        updateCar_Button = new javax.swing.JButton();
        carDetailInformation_Button = new javax.swing.JButton();
        findCar_Button = new javax.swing.JButton();
        butInsurance_Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        car_Number = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_Menu = new javax.swing.JMenu();
        exmportOut_MenuItem = new javax.swing.JMenuItem();
        help_Menu = new javax.swing.JMenu();
        useHelp_MenuItem = new javax.swing.JMenuItem();
        about_MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("车辆列表");
        setLocation(new java.awt.Point(400, 200));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(970, 640));
        setResizable(false);

        jTable1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "车牌号", "车主姓名", "注册日期", "发证日期", "发动机号", "识别代码", "使用性质", "品牌型号", "车辆类型", "备注"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(24);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        addCar_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addCar_Button.setText("添加车辆");
        addCar_Button.setActionCommand("添加");
        addCar_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCar_Button.setFocusable(false);
        addCar_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addCar_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addCar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCar_ButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(addCar_Button);

        deleteCar_Button1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        deleteCar_Button1.setText("删除车辆");
        deleteCar_Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteCar_Button1.setFocusable(false);
        deleteCar_Button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteCar_Button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteCar_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCar_Button1ActionPerformed(evt);
            }
        });
        jToolBar3.add(deleteCar_Button1);

        updateCar_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCar_Button.setText("修改信息");
        updateCar_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCar_Button.setFocusable(false);
        updateCar_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateCar_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateCar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCar_ButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(updateCar_Button);

        carDetailInformation_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        carDetailInformation_Button.setText("查看详细信息");
        carDetailInformation_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carDetailInformation_Button.setFocusable(false);
        carDetailInformation_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        carDetailInformation_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        carDetailInformation_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carDetailInformation_ButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(carDetailInformation_Button);

        findCar_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        findCar_Button.setText("查找");
        findCar_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        findCar_Button.setFocusable(false);
        findCar_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        findCar_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        findCar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCar_ButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(findCar_Button);

        butInsurance_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        butInsurance_Button.setText("缴纳车险");
        butInsurance_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butInsurance_Button.setFocusable(false);
        butInsurance_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butInsurance_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butInsurance_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInsurance_ButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(butInsurance_Button);

        jLabel3.setText("条");

        car_Number.setText("99");

        jLabel1.setText("共");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(car_Number)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(car_Number)
                            .addComponent(jLabel3)))
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        file_Menu.setText("文件");
        file_Menu.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        file_Menu.setIconTextGap(16);

        exmportOut_MenuItem.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        exmportOut_MenuItem.setText("导出");
        exmportOut_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exmportOut_MenuItemActionPerformed(evt);
            }
        });
        file_Menu.add(exmportOut_MenuItem);

        jMenuBar1.add(file_Menu);

        help_Menu.setText("帮助");
        help_Menu.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        help_Menu.setIconTextGap(16);

        useHelp_MenuItem.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        useHelp_MenuItem.setText("使用说明");
        useHelp_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useHelp_MenuItemActionPerformed(evt);
            }
        });
        help_Menu.add(useHelp_MenuItem);

        about_MenuItem.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        about_MenuItem.setText("关于");
        about_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_MenuItemActionPerformed(evt);
            }
        });
        help_Menu.add(about_MenuItem);

        jMenuBar1.add(help_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findCar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findCar_ButtonActionPerformed
        // TODO add your handling code here:
        new FindCarJFrame(jTable1, car_Number).setVisible(true);
    }//GEN-LAST:event_findCar_ButtonActionPerformed

    private void carDetailInformation_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carDetailInformation_ButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h1>选择条目</h1></html>"), "选择条目", JOptionPane.ERROR_MESSAGE);
        } else {
            if (null == jTable1.getValueAt(row, 0)) {
                JOptionPane.showMessageDialog(null, new JLabel("<html><h1>选择的条目无内容</h1></html>"), "选择条目", JOptionPane.ERROR_MESSAGE);
            } else {
                new DetaliInformationCarJFrame1(new VehicleDao().find(Integer.valueOf(String.valueOf(jTable1.getValueAt(row, 0))))).setVisible(true);
            }
        }
    }//GEN-LAST:event_carDetailInformation_ButtonActionPerformed

    private void deleteCar_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCar_Button1ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h1>选择条目</h1></html>"), "选择条目", JOptionPane.ERROR_MESSAGE);
        } else {
            if (null == jTable1.getValueAt(row, 0)) {
                JOptionPane.showMessageDialog(null, new JLabel("<html><h1>选择的条目无内容</h1></html>"), "选择条目", JOptionPane.ERROR_MESSAGE);
            } else {
                new DeleteCarJFrame(new VehicleDao().find(Integer.valueOf(String.valueOf(jTable1.getValueAt(row, 0))))).setVisible(true);
            }
        }
    }//GEN-LAST:event_deleteCar_Button1ActionPerformed

    private void updateCar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCar_ButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h1>选择条目</h1></html>"), "选择条目", JOptionPane.ERROR_MESSAGE);
        } else {
            if (null == jTable1.getValueAt(row, 0)) {
                JOptionPane.showMessageDialog(null, new JLabel("<html><h1>选择的条目无内容</h1></html>"), "选择条目", JOptionPane.ERROR_MESSAGE);
            } else {
                new UpdateCarJFrame(new VehicleDao().find(Integer.valueOf(String.valueOf(jTable1.getValueAt(row, 0))))).setVisible(true);
            }
        }
    }//GEN-LAST:event_updateCar_ButtonActionPerformed

    private void addCar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCar_ButtonActionPerformed
        // TODO add your handling code here:
        new AddCarJFrame().setVisible(true);
    }//GEN-LAST:event_addCar_ButtonActionPerformed

    private void butInsurance_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInsurance_ButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h1>选择条目</h1></html>"), "选择条目", JOptionPane.ERROR_MESSAGE);
        } else {
            if (null == jTable1.getValueAt(row, 0)) {
                JOptionPane.showMessageDialog(null, new JLabel("<html><h1>选择的条目无内容</h1></html>"), "选择条目", JOptionPane.ERROR_MESSAGE);
            } else {
                new AddInsuranceJFrame(new VehicleDao().find(Integer.valueOf(String.valueOf(jTable1.getValueAt(row, 0))))).setVisible(true);
            }
        }
    }//GEN-LAST:event_butInsurance_ButtonActionPerformed

    private void useHelp_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useHelp_MenuItemActionPerformed
        try {
            java.awt.Desktop.getDesktop().open(new File("帮助文档.CHM"));
        } catch (IOException ex) {
            Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_useHelp_MenuItemActionPerformed

    private void exmportOut_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exmportOut_MenuItemActionPerformed
        // TODO add your handling code here:
        new JTableExportToExcel().chooseFile(jTable1, "//车辆详情.xls");
    }//GEN-LAST:event_exmportOut_MenuItemActionPerformed

    private void about_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_MenuItemActionPerformed
        // TODO add your handling code here:
        new AboutJFrame().setVisible(true);
    }//GEN-LAST:event_about_MenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about_MenuItem;
    private javax.swing.JButton addCar_Button;
    private javax.swing.JButton butInsurance_Button;
    private javax.swing.JButton carDetailInformation_Button;
    private javax.swing.JLabel car_Number;
    private javax.swing.JButton deleteCar_Button1;
    private javax.swing.JMenuItem exmportOut_MenuItem;
    private javax.swing.JMenu file_Menu;
    private javax.swing.JButton findCar_Button;
    private javax.swing.JMenu help_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JButton updateCar_Button;
    private javax.swing.JMenuItem useHelp_MenuItem;
    // End of variables declaration//GEN-END:variables
}
