/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.carJFrame;

import Dao.VehicleDao;
import JFrame.customJFrame.CustomerChooseJFrame;
import JFrame.insuranceJFrame.UpdateInsuranceJFrame;
import Po.Vehicle;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 健鑫
 */
public class UpdateCarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddCarJFrame
     */
    private javax.swing.JLabel jLabel;
    private Vehicle vehicle;
    public UpdateCarJFrame(Vehicle v) {
        jLabel=new javax.swing.JLabel();
        vehicle=v;
        jLabel.setText(String.valueOf(vehicle.getV_Owner_ID()));
        initComponents();
    }
    public UpdateCarJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UpdateCar_PlantNumber_TextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UpdateCar_Remark_TextField = new javax.swing.JTextArea();
        UpdateCar_GiveNumber_TextField = new javax.swing.JTextField();
        UpdateCar_EngineNumber_TextField = new javax.swing.JTextField();
        UpdateCar_VIN_TextField = new javax.swing.JTextField();
        UpdateCar_Model_TextField = new javax.swing.JTextField();
        UpdateCar_UerCharactor_TextField = new javax.swing.JTextField();
        UpdateCar_Type_TextField = new javax.swing.JTextField();
        UpdateCar_RegisterDate_TextField = new javax.swing.JTextField();
        updataCar_OK_Button = new javax.swing.JButton();
        updateCar_Cancel_Button = new javax.swing.JButton();
        UpdateCar_ChooseOwner_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("修改信息");

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("车牌号：");

        UpdateCar_PlantNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_PlantNumber_TextField.setText(vehicle.getV_Plante_Nomber());

        jButton1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jButton1.setText("选择车主");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("注册日期：");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("发证日期：");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setText("发动机号：");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("识别代码：");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel6.setText("品牌型号：");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setText("使用性质：");

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel8.setText("车辆类型：");

        jLabel9.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel9.setText("备注：");

        UpdateCar_Remark_TextField.setColumns(20);
        UpdateCar_Remark_TextField.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        UpdateCar_Remark_TextField.setRows(5);
        UpdateCar_Remark_TextField.setText(vehicle.getV_Remark());
        jScrollPane1.setViewportView(UpdateCar_Remark_TextField);

        UpdateCar_GiveNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_GiveNumber_TextField.setText(String.valueOf(vehicle.getV_Give_Date())
        );

        UpdateCar_EngineNumber_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_EngineNumber_TextField.setText(vehicle.getV_Engine_Nomber());

        UpdateCar_VIN_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_VIN_TextField.setText(vehicle.getV_VIN());

        UpdateCar_Model_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_Model_TextField.setText(vehicle.getV_Model());

        UpdateCar_UerCharactor_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_UerCharactor_TextField.setText(vehicle.getV_User_Character());

        UpdateCar_Type_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_Type_TextField.setText(vehicle.getV_Vehicle_Type());

        UpdateCar_RegisterDate_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_RegisterDate_TextField.setText(String.valueOf(vehicle.getV_Register_Date())
        );

        updataCar_OK_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updataCar_OK_Button.setText("确定");
        updataCar_OK_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updataCar_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updataCar_OK_ButtonActionPerformed(evt);
            }
        });

        updateCar_Cancel_Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        updateCar_Cancel_Button.setText("取消");
        updateCar_Cancel_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateCar_Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCar_Cancel_ButtonActionPerformed(evt);
            }
        });

        UpdateCar_ChooseOwner_TextField.setEditable(false);
        UpdateCar_ChooseOwner_TextField.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        UpdateCar_ChooseOwner_TextField.setText(vehicle.getV_Owner_Name());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(updataCar_OK_Button)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addComponent(jButton1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(UpdateCar_PlantNumber_TextField)
                    .addComponent(UpdateCar_GiveNumber_TextField)
                    .addComponent(UpdateCar_EngineNumber_TextField)
                    .addComponent(UpdateCar_VIN_TextField)
                    .addComponent(UpdateCar_Model_TextField)
                    .addComponent(UpdateCar_UerCharactor_TextField)
                    .addComponent(UpdateCar_Type_TextField)
                    .addComponent(UpdateCar_RegisterDate_TextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(updateCar_Cancel_Button))
                    .addComponent(UpdateCar_ChooseOwner_TextField))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(UpdateCar_ChooseOwner_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UpdateCar_PlantNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UpdateCar_RegisterDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UpdateCar_GiveNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(UpdateCar_EngineNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UpdateCar_VIN_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(UpdateCar_Model_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(UpdateCar_UerCharactor_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(UpdateCar_Type_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updataCar_OK_Button)
                    .addComponent(updateCar_Cancel_Button))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateCar_Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCar_Cancel_ButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_updateCar_Cancel_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new CustomerChooseJFrame(jLabel, UpdateCar_ChooseOwner_TextField);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updataCar_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updataCar_OK_ButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");  
        java.util.Date date=null;
        String dstr=null;
                
        vehicle.setV_Engine_Nomber(UpdateCar_EngineNumber_TextField.getText());
        dstr=UpdateCar_GiveNumber_TextField.getText();
         try { 
            date=sdf.parse(dstr);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateInsuranceJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        vehicle.setV_Give_Date(date);
        dstr=UpdateCar_RegisterDate_TextField.getText();
         try { 
            date=sdf.parse(dstr);
        } catch (ParseException ex) {
            Logger.getLogger(UpdateInsuranceJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        vehicle.setV_Register_Date(date);
        vehicle.setV_Model(UpdateCar_Model_TextField.getText());
        vehicle.setV_Owner_ID(Integer.valueOf(jLabel.getText()));
        vehicle.setV_Plante_Nomber(UpdateCar_PlantNumber_TextField.getText());
        vehicle.setV_Remark(UpdateCar_Remark_TextField.getText());
        vehicle.setV_User_Character(UpdateCar_UerCharactor_TextField.getText());
        vehicle.setV_VIN(UpdateCar_VIN_TextField.getText());
        vehicle.setV_Vehicle_Type(UpdateCar_Type_TextField.getText());
        new VehicleDao().update(vehicle);
        
        
        dispose();
    }//GEN-LAST:event_updataCar_OK_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UpdateCar_ChooseOwner_TextField;
    private javax.swing.JTextField UpdateCar_EngineNumber_TextField;
    private javax.swing.JTextField UpdateCar_GiveNumber_TextField;
    private javax.swing.JTextField UpdateCar_Model_TextField;
    private javax.swing.JTextField UpdateCar_PlantNumber_TextField;
    private javax.swing.JTextField UpdateCar_RegisterDate_TextField;
    private javax.swing.JTextArea UpdateCar_Remark_TextField;
    private javax.swing.JTextField UpdateCar_Type_TextField;
    private javax.swing.JTextField UpdateCar_UerCharactor_TextField;
    private javax.swing.JTextField UpdateCar_VIN_TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updataCar_OK_Button;
    private javax.swing.JButton updateCar_Cancel_Button;
    // End of variables declaration//GEN-END:variables
}
